import {
  drPoker,
  gooseBoomBang,
  deadMenWalking,
  gatesUnderworld,
  duckHunters,
  veracruzWild,
  wildTiger2,
  pinball,
  reelRacer,
} from "@/assets/images/home/newreleases";
import { r1, r2, r3, r4, r5, r6 } from "@/assets/images/home/recent";
import { cases, chicken, darts, dice, hilo, keno, limbo, mines, packs, plinko } from "@/assets/images/lobby/slots";

import { StaticImageData } from "next/image";

export interface Game {
  id: number;
  name: string;
  provider:
    | "Pragmatic Play"
    | "Betsoft"
    | "NetEnt"
    | "Wolf Originals"
    | "IGT"
    | "Live Casino"
    | "Evolve";
  category:
    | "Slots"
    | "Table Games"
    | "Live Dealers"
    | "Poker"
    | "Originals"
    | "Live Casino"
    | "Arcade"
    | "Wolf Originals";
  img: StaticImageData;
}

export const mockGames: Game[] = [
  {
    id: 1,
    name: "Goose Boom Bang",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: gooseBoomBang,
  },
  {
    id: 2,
    name: "Dr. Poker Creepy Monster",
    provider: "Betsoft",
    category: "Live Casino",
    img: drPoker,
  },
  {
    id: 3,
    name: "Dead Men Walking",
    provider: "NetEnt",
    category: "Slots",
    img: deadMenWalking,
  },
  {
    id: 4,
    name: "Gates of the Underworld",
    provider: "Pragmatic Play",
    category: "Slots",
    img: gatesUnderworld,
  },
  {
    id: 5,
    name: "Duck Hunters",
    provider: "Evolve",
    category: "Originals",
    img: duckHunters,
  },
  {
    id: 6,
    name: "Veracruz Wild",
    provider: "Betsoft",
    category: "Live Casino",
    img: veracruzWild,
  },
  {
    id: 7,
    name: "Wild Tiger 2",
    provider: "NetEnt",
    category: "Live Casino",
    img: wildTiger2,
  },
  {
    id: 8,
    name: "Pinball Street",
    provider: "IGT",
    category: "Table Games",
    img: pinball,
  },
  {
    id: 9,
    name: "Reel Racer",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: reelRacer,
  },

  // ---- DUPLICATES FOR SCROLL / PAGINATION ----

  {
    id: 10,
    name: "Goose Boom Bang",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: gooseBoomBang,
  },
  {
    id: 11,
    name: "Dr. Poker Creepy Monster",
    provider: "Betsoft",
    category: "Arcade",
    img: drPoker,
  },
  {
    id: 12,
    name: "Dead Men Walking",
    provider: "NetEnt",
    category: "Slots",
    img: deadMenWalking,
  },
  {
    id: 13,
    name: "Gates of the Underworld",
    provider: "Pragmatic Play",
    category: "Slots",
    img: gatesUnderworld,
  },
  {
    id: 14,
    name: "Duck Hunters",
    provider: "Evolve",
    category: "Originals",
    img: duckHunters,
  },
  {
    id: 15,
    name: "Veracruz Wild",
    provider: "Betsoft",
    category: "Slots",
    img: veracruzWild,
  },
  {
    id: 16,
    name: "Wild Tiger 2",
    provider: "NetEnt",
    category: "Slots",
    img: wildTiger2,
  },
  {
    id: 17,
    name: "Pinball Street",
    provider: "IGT",
    category: "Table Games",
    img: pinball,
  },
  {
    id: 18,
    name: "Reel Racer",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: reelRacer,
  },
  {
    id: 19,
    name: "Goose Boom Rush",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: gooseBoomBang,
  },
  {
    id: 20,
    name: "Poker Night Creeps",
    provider: "Betsoft",
    category: "Originals",
    img: drPoker,
  },
  {
    id: 21,
    name: "Walking Shadows",
    provider: "NetEnt",
    category: "Slots",
    img: deadMenWalking,
  },
  {
    id: 22,
    name: "Underworld Gates X",
    provider: "Pragmatic Play",
    category: "Originals",
    img: gatesUnderworld,
  },
  {
    id: 23,
    name: "Hunters Reloaded",
    provider: "Evolve",
    category: "Originals",
    img: duckHunters,
  },
  {
    id: 24,
    name: "Wild Veracruz Nights",
    provider: "Betsoft",
    category: "Slots",
    img: veracruzWild,
  },
  {
    id: 25,
    name: "Tiger Fury 2",
    provider: "NetEnt",
    category: "Slots",
    img: wildTiger2,
  },
  {
    id: 26,
    name: "Pinball Royale",
    provider: "IGT",
    category: "Table Games",
    img: pinball,
  },
  {
    id: 27,
    name: "Reel Racer Pro",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: reelRacer,
  },
  {
    id: 28,
    name: "Boom Bang Extreme",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: gooseBoomBang,
  },
  {
    id: 29,
    name: "Doctor Poker Dark",
    provider: "Betsoft",
    category: "Poker",
    img: drPoker,
  },
  {
    id: 30,
    name: "Dead Walkers Gold",
    provider: "NetEnt",
    category: "Slots",
    img: deadMenWalking,
  },
  {
    id: 31,
    name: "Gates of Chaos",
    provider: "Pragmatic Play",
    category: "Slots",
    img: gatesUnderworld,
  },
  {
    id: 32,
    name: "Duck Hunters Arena",
    provider: "Evolve",
    category: "Originals",
    img: duckHunters,
  },
  {
    id: 33,
    name: "Veracruz Wild Spin",
    provider: "Betsoft",
    category: "Slots",
    img: veracruzWild,
  },
  {
    id: 34,
    name: "Tiger Strike 2",
    provider: "NetEnt",
    category: "Slots",
    img: wildTiger2,
  },
  {
    id: 35,
    name: "Pinball Legends",
    provider: "IGT",
    category: "Table Games",
    img: pinball,
  },
  {
    id: 36,
    name: "Reel Racer Turbo",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: reelRacer,
  },
  {
    id: 37,
    name: "Boom Bang Legends",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: gooseBoomBang,
  },
  {
    id: 38,
    name: "Poker Creepy Nights",
    provider: "Betsoft",
    category: "Poker",
    img: drPoker,
  },
  {
    id: 39,
    name: "Dead Men Rising",
    provider: "NetEnt",
    category: "Slots",
    img: deadMenWalking,
  },
  {
    id: 40,
    name: "Underworld Inferno",
    provider: "Pragmatic Play",
    category: "Table Games",
    img: gatesUnderworld,
  },
  {
    id: 41,
    name: "Duck Hunters X",
    provider: "Evolve",
    category: "Originals",
    img: duckHunters,
  },
  {
    id: 42,
    name: "Veracruz Wild Storm",
    provider: "Betsoft",
    category: "Live Casino",
    img: veracruzWild,
  },
  {
    id: 43,
    name: "Wild Tiger Rampage",
    provider: "NetEnt",
    category: "Live Casino",
    img: wildTiger2,
  },
  {
    id: 44,
    name: "Pinball Classic",
    provider: "IGT",
    category: "Live Casino",
    img: pinball,
  },
  {
    id: 45,
    name: "Reel Racer Nitro",
    provider: "Pragmatic Play",
    category: "Table Games",
    img: reelRacer,
  },
  {
    id: 46,
    name: "Boom Bang Reloaded",
    provider: "Pragmatic Play",
    category: "Poker",
    img: gooseBoomBang,
  },
  {
    id: 47,
    name: "Doctor Poker Midnight",
    provider: "Betsoft",
    category: "Slots",
    img: drPoker,
  },
  {
    id: 48,
    name: "Walking Deadlines",
    provider: "NetEnt",
    category: "Slots",
    img: deadMenWalking,
  },
  {
    id: 49,
    name: "Gates of Abyss",
    provider: "Pragmatic Play",
    category: "Slots",
    img: gatesUnderworld,
  },
  {
    id: 50,
    name: "Duck Hunters Survival",
    provider: "Evolve",
    category: "Originals",
    img: duckHunters,
  },
  {
    id: 51,
    name: "Veracruz Wild Heat",
    provider: "Betsoft",
    category: "Slots",
    img: veracruzWild,
  },
  {
    id: 52,
    name: "Tiger Claw 2",
    provider: "NetEnt",
    category: "Slots",
    img: wildTiger2,
  },
  {
    id: 53,
    name: "Pinball Masters",
    provider: "IGT",
    category: "Arcade",
    img: pinball,
  },
  {
    id: 54,
    name: "Reel Racer Velocity",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: reelRacer,
  },
  {
    id: 55,
    name: "Boom Bang Chaos",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: gooseBoomBang,
  },
  {
    id: 56,
    name: "Poker Creeps Vault",
    provider: "Betsoft",
    category: "Poker",
    img: drPoker,
  },
  {
    id: 57,
    name: "Dead Men Reborn",
    provider: "NetEnt",
    category: "Slots",
    img: deadMenWalking,
  },
  {
    id: 58,
    name: "Underworld Dominion",
    provider: "Pragmatic Play",
    category: "Table Games",
    img: gatesUnderworld,
  },
  {
    id: 59,
    name: "Duck Hunters Prime",
    provider: "Evolve",
    category: "Originals",
    img: duckHunters,
  },
  {
    id: 60,
    name: "Veracruz Wild Flame",
    provider: "Betsoft",
    category: "Slots",
    img: veracruzWild,
  },
  {
    id: 61,
    name: "Tiger Roar 2",
    provider: "NetEnt",
    category: "Slots",
    img: wildTiger2,
  },
  {
    id: 62,
    name: "Pinball Supreme",
    provider: "IGT",
    category: "Table Games",
    img: pinball,
  },
  {
    id: 63,
    name: "Reel Racer Apex",
    provider: "Pragmatic Play",
    category: "Live Dealers",
    img: reelRacer,
  },
  {
    id: 64,
    name: "Boom Bang Infinite",
    provider: "Pragmatic Play",
    category: "Arcade",
    img: gooseBoomBang,
  },
  {
    id: 65,
    name: "Doctor Poker Phantom",
    provider: "Betsoft",
    category: "Arcade",
    img: drPoker,
  },
  {
    id: 66,
    name: "Dead Walkers X",
    provider: "NetEnt",
    category: "Poker",
    img: deadMenWalking,
  },
  {
    id: 67,
    name: "Gates of Oblivion",
    provider: "Pragmatic Play",
    category: "Table Games",
    img: gatesUnderworld,
  },
  {
    id: 68,
    name: "Duck Hunters Unlimited",
    provider: "Evolve",
    category: "Table Games",
    img: duckHunters,
  },
  {
    id: 69,
    name: "Veracruz Wild Rush",
    provider: "Betsoft",
    category: "Table Games",
    img: veracruzWild,
  },
  {
    id: 70,
    name: "Tiger Storm 2",
    provider: "NetEnt",
    category: "Live Dealers",
    img: wildTiger2,
  },
  {
    id: 71,
    name: "Pinball Infinite",
    provider: "IGT",
    category: "Arcade",
    img: pinball,
  },
  {
    id: 72,
    name: "Reel Racer Overdrive",
    provider: "Pragmatic Play",
    category: "Live Dealers",
    img: reelRacer,
  },
   { id:75, name:"Mines", provider:"Wolf Originals", category:"Table Games", img:mines },
  { id:76, name:"Plinko", provider:"Wolf Originals", category:"Table Games", img:plinko },
  { id:77, name:"Chicken", provider:"Wolf Originals", category:"Live Dealers", img:chicken },
  { id:78, name:"Crash", provider:"Wolf Originals", category:"Table Games", img:cases },
  { id:79, name:"Keno", provider:"Wolf Originals", category:"Arcade", img:keno },
  { id:80, name:"Limbo", provider:"Wolf Originals", category:"Arcade", img:limbo },
  { id:81, name:"HILO", provider:"Wolf Originals", category:"Arcade", img:hilo },
  { id:82, name:"PACKS", provider:"Wolf Originals", category:"Table Games", img:packs },
  { id:83, name:"Darts", provider:"Wolf Originals", category:"Table Games", img:darts },

  { id:84, name:"Dice Pro", provider:"Wolf Originals", category:"Table Games", img:dice },
  { id:85, name:"Mines X", provider:"Wolf Originals", category:"Live Dealers", img:mines },
  { id:86, name:"Plinko Plus", provider:"Wolf Originals", category:"Live Casino", img:plinko },
  { id:87, name:"Chicken Run", provider:"Wolf Originals", category:"Arcade", img:chicken },
  { id:88, name:"Crash Turbo", provider:"Wolf Originals", category:"Live Dealers", img:cases },
  { id:89, name:"Keno Max", provider:"Wolf Originals", category:"Live Casino", img:keno },
  { id:90, name:"Limbo Extreme", provider:"Wolf Originals", category:"Table Games", img:limbo },
  { id:91, name:"HILO Advance", provider:"Wolf Originals", category:"Arcade", img:hilo },
  { id:92, name:"PACKS Gold", provider:"Wolf Originals", category:"Live Casino", img:packs },
  { id:93, name:"Darts Pro", provider:"Wolf Originals", category:"Arcade", img:darts },

  /* ---- WINS CONVERTED TO SAME FORMAT ---- */

  { id:94, name:"Crazy Time", provider:"Wolf Originals", category:"Live Casino", img:r1 },
  { id:95, name:"Wanted", provider:"Wolf Originals", category:"Live Casino", img:r2 },
  { id:96, name:"Wanted", provider:"Wolf Originals", category:"Live Casino", img:r3 },
  { id:97, name:"PLINKO", provider:"Wolf Originals", category:"Table Games", img:r4 },
  { id:98, name:"PLINKO", provider:"Wolf Originals", category:"Live Casino", img:r5 },
  { id:99, name:"RETRO SWEETS", provider:"Wolf Originals", category:"Slots", img:r6 },
  { id:100, name:"Crazy Time", provider:"Wolf Originals", category:"Live Casino", img:r1 },
  { id:101, name:"Wanted", provider:"Wolf Originals", category:"Slots", img:r2 },
  { id:102, name:"Wanted", provider:"Wolf Originals", category:"Slots", img:r3 },
  { id:103, name:"PLINKO", provider:"Wolf Originals", category:"Table Games", img:r4 },
];